DROP TABLE IF EXISTS tests;


CREATE TABLE tests(
id SERIAL2 PRIMARY KEY,
BASE VARCHAR(255),
ETH DECIMAL,
BTC DECIMAL,
USD DECIMAL,
EUR DECIMAL,
GBP DECIMAL,
tstamp_unix INT8 DEFAULT (extract(epoch from now())*1000),
tstamp_readable TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

